### ISSUE TITLE
Getting BrokenPipeError when trying to send logs on shutdown

### ISSUE THREAD

**Issue by carver** [ethereum/trinity#1381]
### What is wrong?

Getting an absolute deluge of logs (about broken logs) on shutdown. It requires multiple `ctrl-c` before it finally stops. This is pretty recent.

One of: #1307 

### How can it be fixed

I guess the logging pipe is being closed before some other processes have finished shutting down?

**Comment by pipermerriam** [comment]
I thought I had this clean but this was introduced in #1328 

I am pretty sure I have it fixed in #1363 which I think I'm almost done with.

**Comment by carver** [comment]
Hmm, seems like it's still happening. Were you able to reproduce the failure and then fix locally?

**Comment by pipermerriam** [comment]
I'm still narrowing in on this stuff.  I don't have anything concrete but the problem should be *better* now than it was before, and now I can narrow in on why the logging connection is closed even though it's still within the context block.

My two ideas right now are:

1. The parent process has actually already closed the logger server. (less likely)
2. There's still some asyncio loop stuff happening when it should already be shut down...   

Neither of these make any logical sense to me based on how the code *should* run, but I feel like I'm starting to gain some better intuition about how everything runs after throwing myself at it for a few weeks.  I continue to *feel* like the new service model is going to clean a lot of this up so I'm starting to chip away at that too...

**Comment by cburgdorf** [comment]
I just came here to note that I see exactly the same flood of errors on shutdown.

**Comment by gsalgado** [comment]
Should this be closed in favour of #1558?

**Comment by carver** [comment]
> Should this be closed in favour of #1558?

Maybe the other way around, since this one has more commentary. Worth briefly noting that #1558 had a slightly different message, but probably the same cause:
```
--- Logging error ---
Traceback (most recent call last):
  File "/home/jcarver/code/trinity/trinity/db/manager.py", line 150, in serve_conn
    operation_byte = sock.read_exactly(1)
  File "/home/jcarver/code/trinity/trinity/_utils/socket.py", line 27, in read_exactly
    raise OSError("Connection closed")
OSError: Connection closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jcarver/code/trinity/trinity/_utils/logging.py", line 76, in emit
    self._socket.sendall(msg_length_data + msg_data)
OSError: [Errno 9] Bad file descriptor
```

(Bad file descriptor instead of `BrokenPipeError`)

**Comment by gsalgado** [comment]
I'm no longer seeing this, so closing for now
